---
dependencies: []

galaxy_info:
  author: yfix
  description: PHP for RedHat/CentOS/Debian/Ubuntu.
  company: "Yfix group"
  license: "license (MIT)"
  min_ansible_version: 1.8
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  categories:
    - development
    - web
