---
# Pass in a comma-separated list of repos to use (e.g. "remi,epel").
php_enablerepo: ""

# Set this to false if you're not using PHP with Apache/Nginx/etc.
php_enable_webserver: true

# Start and enable the PHP fpm service.
php_enable_php_fpm: false

# The executable to run when calling PHP from the command line.
php_executable: "php"

# If this is set to false, none of the following options will have any effect.
# Any and all changes to /etc/php.ini will be your responsibility.
php_use_managed_ini: true

php_expose_php: "On"
php_memory_limit: "256M"
php_max_execution_time: "60"
php_max_input_time: "60"
php_max_input_vars: "1000"
php_realpath_cache_size: "32K"
php_upload_max_filesize: "64M"
php_post_max_size: "32M"
php_date_timezone: "America/Chicago"

php_sendmail_path: "/usr/sbin/sendmail -t -i"
php_short_open_tag: false

php_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
php_display_errors: "Off"
php_display_startup_errors: "Off"
