---
dependencies: []

galaxy_info:
  author: yfix
  description: Basic system configuration changes, tweaks and fixes.
  company: "Yfix group"
  license: "license (MIT)"
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  categories:
    - system
