---
dependencies: []

galaxy_info:
  author: yfix
  description: Memcached for Linux
  company: "Yfix group"
  license: "license (MIT)"
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
    - precise
    - trusty
  - name: Debian
    versions:
    - all
  categories:
    - web
    - database
