---
# Include OS-specific installation tasks.
- include: setup-Debian.yml
  when: (ruby_install_from_source == false) and (ansible_os_family == 'Debian')

# Install Bundler and configured gems.
- name: Install Bundler.
  gem: name=bundler state=present user_install=no

- name: Add bundle symlink.
  file: src=/usr/local/bin/bundle dest=/usr/bin/bundle state=link
  when: ruby_install_from_source == true

- name: Install configured gems.
  gem: "name={{ item }} state=present"
  with_items: ruby_install_gems
